title: Stackbit Libris Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
palette: blue
header:
  title: IEEE MOVE Radio Club
  logo_img: images/MOVE.jpg
  logo_img_alt: IEEE MOVE logo
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
      has_subnav: false
    - label: Docs
      url: /docs
      style: link
      has_subnav: false
footer:
  content: >-
     Updated - August 2021
  has_social: false
  social_links:
    - label: Twitter
      url: 'https://twitter.com/'
      style: icon
      icon_class: twitter
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      style: icon
      icon_class: linkedin
      new_window: true
    - label: GitHub
      url: 'https://github.com/'
      style: icon
      icon_class: github
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
domain: 'https://radioclub.moveteams.org'
google-space: 'https://drive.google.com/drive/folders/1wBDvV5gWA_-wGpIm_g64aLZXrF48YPoB?usp=sharing'